### ISSUE TITLE
Main - закрытие всех процессов

### ISSUE THREAD

**Issue by aademid** [NIBugakov/rivegaucheUipath#1]
Снова забыл настроить :(

**Comment by NIBugakov** [comment]
Беда ,видимо ,я пока не обжегся ,сложно навсегда это запомнить ,но постараюсь

**Comment by aademid** [comment]
Так и не поправил? - a88d5ba7297033a8416a67a4f0614c9e66fb8c4b

**Comment by NIBugakov** [comment]
Не сохранилось (

**Comment by aademid** [comment]
Исправлено - 9aa7207fb2719cc01502c6353ead6bde500706bf

**Comment by aademid** [comment]
9aa7207fb2719cc01502c6353ead6bde500706bf
