### ISSUE TITLE
Create Transaction - Use Browser

### ISSUE THREAD

**Issue by aademid** [NIBugakov/rivegaucheUipath#2]
Не настроен селектор
Указана ссылка - можно удалить

**Comment by NIBugakov** [comment]
Исправил ,не понял ,какой селектор ,который делает таблицы ?

**Comment by aademid** [comment]
> Исправил ,не понял ,какой селектор ,который делает таблицы ?

Если правильно помню - селектор подключения к браузеру, там что то не так было
после всех исправлений точно скажу)

**Comment by aademid** [comment]
Исправлено - a88d5ba7297033a8416a67a4f0614c9e66fb8c4b
