### ISSUE TITLE
Process - Проверка существования выбора обьема

### ISSUE THREAD

**Issue by aademid** [NIBugakov/rivegaucheUipath#4]
Не отредактирован селектор (пробелы)

**Comment by aademid** [comment]
"Поиск всех дочерних обьектов поля обьем"
Скорректирован но тоже пробел один пропущен

**Comment by aademid** [comment]
Process - Проверка существования выбора цвета
Тоже самое, селектор можно настроить лучше

**Comment by aademid** [comment]
ExtractData - Проверка существования поля обьема
Селектор

**Comment by aademid** [comment]
ExtractData - Проверка существования поля обьема ( проверка "доступен только онлайн")
Селектор

**Comment by aademid** [comment]
Extract Data - Клик В других городах
Селектор

**Comment by NIBugakov** [comment]
Злодей ,пытки устраиваешь своими этими пробелами ,кроме пробелов ,ничего плохого в селекторах не вижу

**Comment by aademid** [comment]
> Злодей ,пытки устраиваешь своими этими пробелами ,кроме пробелов ,ничего плохого в селекторах не вижу

После редактирования пробелов проверь корректность селекторов, вчера при проверке парочку сломались, как только пробелы заменил на звездочки

Некоторые селекторы придется перевыбрать\перенастроить (например используется innerText как атрибут, а нужно перевыбрать на aaname)

**Comment by NIBugakov** [comment]
Запустил ради интереса ,вроде все работает

**Comment by aademid** [comment]
Исправлено - a88d5ba7297033a8416a67a4f0614c9e66fb8c4b
