### ISSUE TITLE
Process - извлечение цвета

### ISSUE THREAD

**Issue by aademid** [NIBugakov/rivegaucheUipath#5]
Некорректное описание (написано про извлечение объема)
Слишком нагружено, можно заменить активностью извлечения таблицы по хорошему

**Comment by NIBugakov** [comment]
Исправил описание

**Comment by aademid** [comment]
Нагруженность

**Comment by aademid** [comment]
Извлечение объема можно тоже фильтр на дочерние элементы настроить

**Comment by aademid** [comment]
Process - Повторение т.к. иногда цвета не подгружаются быстро - в целом можно как с названием товара придумать что то

**Comment by aademid** [comment]
Лишние шаги оставил Process - для каждого найденного объекта (цвета) 
До этого сделал поиск элементов с фильтром, можно сразу в цикле извлечь URL и закинуть в лист

Цикл с проверкой забыл скорее всего убрать после доработки данного места (он бесполезен теперь)

**Comment by aademid** [comment]
Исправлено - 9aa7207fb2719cc01502c6353ead6bde500706bf
