### ISSUE TITLE
Extract Data - Получение числового значения  id

### ISSUE THREAD

**Issue by aademid** [NIBugakov/rivegaucheUipath#7]
Регулярка так себе
И вероятно она излишняя, проще Remove("ID: ")

Регулярки круто, но если проще обойтись без них - почему бы и нет

**Comment by NIBugakov** [comment]
А зачем мы тогда перед этим целый курс регулярок проходим ?)

**Comment by aademid** [comment]
> А зачем мы тогда перед этим целый курс регулярок проходим ?)

Даже если оставлять регулярку, то лучше ее поправить чем оставить - "все символы после пробела"
Но регулярки и в следующих заданиях будут, не переживай)

**Comment by NIBugakov** [comment]
Исправил сделал привязку по id
![image](https://github.com/NIBugakov/rivegaucheUipath/assets/159261560/613ad5b0-c2d1-49c7-83a0-01e68a82b254)

**Comment by aademid** [comment]
Все равно не до конца доделал, теперь другая проблема (неверные данные) - https://github.com/NIBugakov/rivegaucheUipath/issues/13
