### ISSUE TITLE
Extract Data - Извлечение объема из названия товара

### ISSUE THREAD

**Issue by aademid** [NIBugakov/rivegaucheUipath#8]
Очень сомнительное решение с точки зрения стабильности
В товарах всегда есть характеристика и сам элемент с указанным объемом

**Comment by NIBugakov** [comment]
Так 
![image](https://github.com/NIBugakov/rivegaucheUipath/assets/159261560/bf920290-a553-41da-9be1-c720c6e4c85c)

**Comment by aademid** [comment]
Исправлено регулярное выражение, решение аргументировано - a88d5ba7297033a8416a67a4f0614c9e66fb8c4b
